import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <ul className=" py-4 px-2 flex gap-3">
              <li>
                <Link
                  className="bg-black py-4 px-2 text-white rounded-md"
                  href={"/whileDrag/"}
                >
                  whileDrag
                </Link>
              </li>
              <li>
                <Link
                  className="bg-black py-4 px-2 text-white rounded-md"
                  href={"/gestures/"}
                >
                  Gestures
                </Link>
              </li>
              <li>
                <Link
                  className="bg-black py-4 px-2 text-white rounded-md"
                  href={"/"}
                >
                  Home
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main> {children}</main>
      </body>
    </html>
  );
}
